<a href="https://colab.research.google.com/github/madol-abraham/Formative-Assignment-PCA/blob/main/Formative_Assignment_PCA_%5BMadol_Abraham_Kuol_Madol%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [ ]:
#import necessary package
#TO DO
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


load the dataset

In [ ]:
fuel_econ = pd.read_csv("/content/drive/MyDrive/Machine_learning/fuel_econ.csv")

# display the dataset
fuel_econ

id        make             model  year           VClass  \
0     32204      Nissan              GT-R  2013  Subcompact Cars   
1     32205  Volkswagen                CC  2013     Compact Cars   
2     32206  Volkswagen                CC  2013     Compact Cars   
3     32207  Volkswagen        CC 4motion  2013     Compact Cars   
4     32208   Chevrolet    Malibu eAssist  2013     Midsize Cars   
...     ...         ...               ...   ...              ...   
3924  39882      Toyota       Prius Prime  2018     Midsize Cars   
3925  39898     Hyundai     Sonata Hybrid  2018     Midsize Cars   
3926  39899     Hyundai  Sonata Hybrid SE  2018     Midsize Cars   
3927  39900       Lexus            LS 500  2018     Midsize Cars   
3928  39901       Lexus        LS 500 AWD  2018     Midsize Cars   

                  drive                             trans          fuelType  \
0       All-Wheel Drive                   Automatic (AM6)  Premium Gasoline   
1     Front-Wheel Drive                 Automatic (AM-S6)  Premium Gasoline   
2     Front-Wheel Drive                    Automatic (S6)  Premium Gasoline   
3       All-Wheel Drive                    Automatic (S6)  Premium Gasoline   
4     Front-Wheel Drive                    Automatic (S6)  Regular Gasoline   
...                 ...                               ...               ...   
3924  Front-Wheel Drive  Automatic (variable gear ratios)  Regular Gasoline   
3925  Front-Wheel Drive                   Automatic (AM6)  Regular Gasoline   
3926  Front-Wheel Drive                   Automatic (AM6)  Regular Gasoline   
3927   Rear-Wheel Drive                   Automatic (S10)  Premium Gasoline   
3928    All-Wheel Drive                   Automatic (S10)  Premium Gasoline   

      cylinders  displ  pv2  pv4     city    UCity  highway  UHighway  \
0             6    3.8   79    0  16.4596  20.2988  22.5568   30.1798   
1             4    2.0   94    0  21.8706  26.9770  31.0367   42.4936   
2             6    3.6   94    0  17.4935  21.2000  26.5716   35.1000   
3             6    3.6   94    0  16.9415  20.5000  25.2190   33.5000   
4             4    2.4    0   95  24.7726  31.9796  35.5340   51.8816   
...         ...    ...  ...  ...      ...      ...      ...       ...   
3924          4    1.8    0    0  55.2206  78.8197  53.0000   73.6525   
3925          4    2.0    0  106  39.0000  55.9000  44.3066   64.0000   
3926          4    2.0    0  106  40.0000  56.0000  46.0000   64.0000   
3927          6    3.4   99    0  19.2200  24.2000  30.2863   43.4000   
3928          6    3.4   99    0  18.0431  22.6000  27.0000   39.3000   

         comb  co2  feScore  ghgScore  
0     18.7389  471        4         4  
1     25.2227  349        6         6  
2     20.6716  429        5         5  
3     19.8774  446        5         5  
4     28.6813  310        8         8  
...       ...  ...      ...       ...  
3924  54.4329   78       10        10  
3925  41.0000  217        9         9  
3926  42.0000  212        9         9  
3927  23.0021  387        5         5  
3928  21.3945  417        4         4  

[3929 rows x 20 columns]

In [ ]:
#display the first five(5) rows of the dataset to comprehend the structure of the dataset
fuel_econ.head(5)

id        make           model  year           VClass  \
0  32204      Nissan            GT-R  2013  Subcompact Cars   
1  32205  Volkswagen              CC  2013     Compact Cars   
2  32206  Volkswagen              CC  2013     Compact Cars   
3  32207  Volkswagen      CC 4motion  2013     Compact Cars   
4  32208   Chevrolet  Malibu eAssist  2013     Midsize Cars   

               drive              trans          fuelType  cylinders  displ  \
0    All-Wheel Drive    Automatic (AM6)  Premium Gasoline          6    3.8   
1  Front-Wheel Drive  Automatic (AM-S6)  Premium Gasoline          4    2.0   
2  Front-Wheel Drive     Automatic (S6)  Premium Gasoline          6    3.6   
3    All-Wheel Drive     Automatic (S6)  Premium Gasoline          6    3.6   
4  Front-Wheel Drive     Automatic (S6)  Regular Gasoline          4    2.4   

   pv2  pv4     city    UCity  highway  UHighway     comb  co2  feScore  \
0   79    0  16.4596  20.2988  22.5568   30.1798  18.7389  471        4   
1   94    0  21.8706  26.9770  31.0367   42.4936  25.2227  349        6   
2   94    0  17.4935  21.2000  26.5716   35.1000  20.6716  429        5   
3   94    0  16.9415  20.5000  25.2190   33.5000  19.8774  446        5   
4    0   95  24.7726  31.9796  35.5340   51.8816  28.6813  310        8   

   ghgScore  
0         4  
1         6  
2         5  
3         5  
4         8

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# converting columns to numerics
data = fuel_econ.select_dtypes(include=[np.number]).values

In [ ]:
data

array([[3.2204e+04, 2.0130e+03, 6.0000e+00, ..., 4.7100e+02, 4.0000e+00,
        4.0000e+00],
       [3.2205e+04, 2.0130e+03, 4.0000e+00, ..., 3.4900e+02, 6.0000e+00,
        6.0000e+00],
       [3.2206e+04, 2.0130e+03, 6.0000e+00, ..., 4.2900e+02, 5.0000e+00,
        5.0000e+00],
       ...,
       [3.9899e+04, 2.0180e+03, 4.0000e+00, ..., 2.1200e+02, 9.0000e+00,
        9.0000e+00],
       [3.9900e+04, 2.0180e+03, 6.0000e+00, ..., 3.8700e+02, 5.0000e+00,
        5.0000e+00],
       [3.9901e+04, 2.0180e+03, 6.0000e+00, ..., 4.1700e+02, 4.0000e+00,
        4.0000e+00]])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

Handling data on the same scale improves model performance, prevents feature bias, and ensures more accurate, interpretable, and faster results.

In [ ]:
# steps to standardize the data

#TO DO:  Insert code here
means = np.mean(data, axis=0)
std_devs = np.std(data, axis=0)
standardized_data = (data - means) / std_devs

In [ ]:
print(standardized_data)

[[-1.73714048 -1.47583548  0.28310163 ...  1.02283829 -0.95057953
  -0.94575548]
 [-1.73668367 -1.47583548 -0.78181585 ... -0.29854998  0.1886082
   0.1942578 ]
 [-1.73622685 -1.47583548  0.28310163 ...  0.56793413 -0.38098566
  -0.37574884]
 ...
 [ 1.77804883  1.4747841  -0.78181585 ... -1.78240402  1.89738979
   1.90427772]
 [ 1.77850564  1.4747841   0.28310163 ...  0.11302997 -0.38098566
  -0.37574884]
 [ 1.77896246  1.4747841   0.28310163 ...  0.43796152 -0.95057953
  -0.94575548]]


![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

In [ ]:
print(standardized_data.shape)


(3929, 14)


### Step 2: Calculate the Covariance Matrix



In [ ]:
# calculating the convariance matrix
covariance_matrix = np.cov(standardized_data, rowvar=False)
covariance_matrix

array([[ 1.00025458,  0.98591866, -0.06011148, -0.07468488, -0.00657025,
        -0.02195656,  0.09182316,  0.09124849,  0.0906161 ,  0.09538375,
         0.09382686, -0.09974229, -0.1279056 , -0.12235207],
       [ 0.98591866,  1.00025458, -0.05532701, -0.07044161,  0.00623397,
        -0.03365174,  0.06806739,  0.06675938,  0.07330836,  0.07766039,
         0.07201181, -0.0811853 , -0.1498676 , -0.14517775],
       [-0.06011148, -0.05532701,  1.00025458,  0.93411019,  0.24763384,
        -0.00426546, -0.69327904, -0.66619842, -0.76646982, -0.77169964,
        -0.73821112,  0.84848979, -0.78405759, -0.78201448],
       [-0.07468488, -0.07044161,  0.93411019,  1.00025458,  0.2594021 ,
         0.02207729, -0.71366074, -0.6863403 , -0.78418374, -0.78865771,
        -0.75859024,  0.85559254, -0.7936343 , -0.79141752],
       [-0.00657025,  0.00623397,  0.24763384,  0.2594021 ,  1.00025458,
        -0.66581137, -0.27817962, -0.27261515, -0.29688365, -0.29858023,
        -0.29095711,  0.28

### Step 3: Eigendecomposition on the Covariance Matrix


In [ ]:
# Eigene values and eigen vectors

eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

In [ ]:
print(eigenvalues)

[8.95720924e+00 2.06777956e+00 1.59364217e+00 6.70587666e-01
 3.01684118e-01 1.61017548e-01 1.25550471e-01 6.40205207e-02
 3.23528963e-02 1.36962433e-02 9.24627112e-03 4.24637785e-03
 2.14358185e-03 3.87485886e-04]


In [ ]:
print(eigenvectors)

[[ 1.89952516e-02 -6.87675276e-01  7.65365183e-02  1.83729680e-02
  -1.42115022e-02  7.02789695e-02  1.14861126e-01  4.01097554e-03
  -1.15143583e-01 -6.95538857e-01 -6.83326435e-02  2.10633586e-02
  -7.10578367e-03  6.07618642e-04]
 [ 1.24694065e-02 -6.89503292e-01  6.88439505e-02 -9.43831862e-03
  -1.35600088e-02  3.37955333e-02  8.53170135e-02 -7.51768613e-03
  -5.48830131e-02  7.10425085e-01  5.58369479e-02 -9.48384475e-03
  -3.26885432e-04 -3.98397374e-03]
 [-2.81632694e-01  1.98550575e-02  5.61398643e-02  6.00933196e-01
   9.71151716e-02 -7.09369930e-02  2.53817629e-01 -6.79764243e-01
   1.19688616e-01  2.20121563e-03  1.99493288e-02  1.60174402e-02
   8.04028190e-03 -8.90395340e-04]
 [-2.86142593e-01  3.10582044e-02  6.39803619e-02  5.69008152e-01
  -1.12579685e-02  5.20085469e-04  2.41804525e-01  7.26076226e-01
   5.26897639e-02  1.88707728e-02  2.64926668e-03  2.74345123e-03
   1.81240405e-02  5.96415755e-03]
 [-1.13744496e-01 -6.35462585e-02 -6.68453743e-01  1.11921299e-01
  

In [ ]:
print(eigenvectors.shape)

(14, 14)


### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [ ]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = np.argsort(eigenvalues)[::-1]
print ( 'the order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[order_of_importance]

print('\n\n sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[:, order_of_importance]
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

the order of importance is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


 sorted eigen values:
[8.95720924e+00 2.06777956e+00 1.59364217e+00 6.70587666e-01
 3.01684118e-01 1.61017548e-01 1.25550471e-01 6.40205207e-02
 3.23528963e-02 1.36962433e-02 9.24627112e-03 4.24637785e-03
 2.14358185e-03 3.87485886e-04]


 The sorted eigen vector matrix is: 
 [[ 1.89952516e-02 -6.87675276e-01  7.65365183e-02  1.83729680e-02
  -1.42115022e-02  7.02789695e-02  1.14861126e-01  4.01097554e-03
  -1.15143583e-01 -6.95538857e-01 -6.83326435e-02  2.10633586e-02
  -7.10578367e-03  6.07618642e-04]
 [ 1.24694065e-02 -6.89503292e-01  6.88439505e-02 -9.43831862e-03
  -1.35600088e-02  3.37955333e-02  8.53170135e-02 -7.51768613e-03
  -5.48830131e-02  7.10425085e-01  5.58369479e-02 -9.48384475e-03
  -3.26885432e-04 -3.98397374e-03]
 [-2.81632694e-01  1.98550575e-02  5.61398643e-02  6.00933196e-01
   9.71151716e-02 -7.09369930e-02  2.53817629e-01 -6.79764243e-01
   1.19688616e-01  2.20121563e-03  1.99493288e-02

Question:

1. Why do we order eigen values and eigen vectors?

Ordering eigenvalues and eigenvectors prioritizes important components, aids dimensionality reduction, separates signal from noise, and improves computational efficiency.

2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

It is not generally true, We prioritize the highest eigenvalues because they capture the most variance and significant information. The lowest eigenvalues often represent noise or less useful components, typically discarded.


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [ ]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

#TO DO: Insert code here
explained_variance = (sorted_eigenvalues / np.sum(sorted_eigenvalues)) * 100
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['63.96%', '14.77%', '11.38%', '4.79%', '2.15%', '1.15%', '0.90%', '0.46%', '0.23%', '0.10%', '0.07%', '0.03%', '0.02%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [ ]:
k =  3

reduced_data = np.matmul(standardized_data, sorted_eigenvectors[:, :k])

In [ ]:
print(reduced_data)

[[-3.19146207  1.98769416 -1.85142805]
 [ 0.38752701  1.99194578 -2.47970321]
 [-2.09148498  2.03743394 -2.20581408]
 ...
 [ 6.84833724 -2.12577829  0.79243213]
 [-0.99151331 -2.51764543 -1.88248871]
 [-1.99449758 -2.60766847 -1.80723835]]


In [ ]:
print(reduced_data.shape)

(3929, 3)


In [ ]:
# expected output for k = 2
reduced_data = np.matmul(standardized_data, sorted_eigenvectors[:, :k])
# reduced_data = np.matmul(standardized_data, sorted_eigenvectors[:, :2])
print(reduced_data)

[[-3.19146207  1.98769416 -1.85142805]
 [ 0.38752701  1.99194578 -2.47970321]
 [-2.09148498  2.03743394 -2.20581408]
 ...
 [ 6.84833724 -2.12577829  0.79243213]
 [-0.99151331 -2.51764543 -1.88248871]
 [-1.99449758 -2.60766847 -1.80723835]]


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations
# **Benefits**:
Dimensionality Reduction:
 PCA reduces the number of features in a dataset, which simplifies analysis, reduces computational cost, and helps with visualization.

Noise Reduction:
By focusing on the principal components that capture the most variance, PCA helps eliminate less significant, noisy data.*
### **Limitations:**
Loss of Information: Reducing dimensions can result in the loss of some data variability, potentially overlooking important information that may be relevant to the analysis .

Interpretability: The transformed features are linear *combinations* of the original features, which may make it difficult to interpret their real-world meaning.